train:
  _target_: src.datasets.RuslanDataset
  data_dir: data
  target_sr: 22050
  shuffle_index: false
  segment_size: 16384
  part: train
  test_size: 10
  instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.RuslanDataset
  data_dir: data
  target_sr: 22050
  shuffle_index: false
  segment_size: 16384
  part: test
  test_size: 10
  instance_transforms: ${transforms.instance_transforms.inference}
