train:
  _target_: src.datasets.RuslanDataset
  wav_path: data/ruslan/RUSLAN
  metadata_path: data/metadata_RUSLAN_22200.csv
  target_sr: 22050
  shuffle_index: false
  limit: 6
  instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.RuslanDataset
  wav_path: data/ruslan/RUSLAN
  metadata_path: data/metadata_RUSLAN_22200.csv
  target_sr: 22050
  shuffle_index: false
  limit: 6
  instance_transforms: ${transforms.instance_transforms.inference}
