defaults:
  s- melspectrogram: melspectrogram
  - model: vocos
  - writer: cometml
  - metrics: empty_metrics
  - datasets: ruslan
  - dataloader: example
  - transforms: vocos
  - _self_

# Dataloader
dataloader:
  num_workers: 4

# Writer
writer:
  run_name: "train"

# Generator optimizer
optimizer:
  _target_: torch.optim.AdamW
  lr: 2e-4
  betas: [0.9, 0.999]

lr_scheduler:
  _target_: torch.optim.lr_scheduler.ConstantLR
  factor: 1.0
  total_iters: 0

# Discriminator optimizer
optimizer_d:
  _target_: torch.optim.AdamW
  lr: 2e-4
  betas: [0.9, 0.999]

lr_scheduler_d:
  _target_: torch.optim.lr_scheduler.ConstantLR
  factor: 1.0
  total_iters: 0

# Loss

loss_function:
  _target_: src.loss.MelSpecReconstructionLoss
  config: ${melspectrogram}

# Discriminators
discriminator_mpd:
  _target_: src.model.MultiPeriodDiscriminator
  periods: [2, 3, 5, 7, 11]

discriminator_mrd:
  _target_: src.model.MultiResolutionDiscriminator
  fft_sizes: [2048, 1024, 512]

# Trainer
trainer:
  trainer_class: VocosTrainer
  mel_spec: ${melspectrogram}
  mel_loss_coeff: 45.0
  feat_loss_coeff: 2.0
  log_step: 50
  n_epochs: 100
  # epoch_len: 10000  # 100 * 10000 = 1M iters (1M G + 1M D updates)
  device_tensors: ["spectrogram", "audio"]
  resume_from: null
  device: auto
  override: True
  monitor: "min val_loss"
  save_period: 1
  save_dir: "saved"
  seed: 1
  max_grad_norm: 10.0
