_target_: src.logger.CometMLWriter
project_name: "vocos_project"
workspace: null
run_name: "onebatch_test"
mode: "online"
loss_names:
    - loss
    - mel_loss
    - gen_loss
    - disc_loss
    - feat_loss
log_checkpoints: False # set to True if you want to log save_dir with checkpoints to W&B
id_length: 32 # length of the run_id
